### PR TITLE
TST: use pysat develop in travis

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

pysat test instruments not currently available in the pip installable version.  Trying a manual install from github to enable testing.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested via Travis CI

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
I forgot about the pip issue. Thought I was starting to go crazy. Thank you!

**Comment by jklenzing** [comment]
There might be other issues.  I'll keep poking at it.

**Comment by jklenzing** [comment]
Should be good to go.

**Comment by rstoneback** [comment]
Thank you!

**Pull request merged**
