### PR TITLE
DOC: Add community docs

### PR DESCRIPTION
**Pull request by jklenzing**
Addresses #19.  Includes:
- issue / pull request templates
- changelog
- code of conduct

### CODE REVIEW

**Review by rstoneback — APPROVED** [review]
Thanks for the community docs

**Comment by jklenzing** [comment]
Don't have write access to this repository, so I can't merge.

**Comment by rstoneback** [comment]
Huh. Ok. Thanks for the heads up. Must be because this one was created back in the day. I’ll take a look at settings later today.

Cheers,
Russell

On Sep 24, 2019, at 10:00 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't have write access to this repository, so I can't merge.

**Comment by rstoneback** [comment]
Test failures are related to changes in pysat, not pysatMagVect. Merging.

**Comment by rstoneback** [comment]
Default permissions for the pysat team are now set to write.

On Sep 24, 2019, at 11:19 AM, Stoneback, Russell <rstoneba@utdallas.edu<mailto:rstoneba@utdallas.edu>> wrote:

Huh. Ok. Thanks for the heads up. Must be because this one was created back in the day. I’ll take a look at settings later today.

Cheers,
Russell

On Sep 24, 2019, at 10:00 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Don't have write access to this repository, so I can't merge.

**Pull request merged**
